
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Management_WebService", targetNamespace = "http://is_assignment3/", wsdlLocation = "http://localhost:8081/management?wsdl")
public class ManagementWebService
    extends Service
{

    private final static URL MANAGEMENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGEMENTWEBSERVICE_EXCEPTION;
    private final static QName MANAGEMENTWEBSERVICE_QNAME = new QName("http://is_assignment3/", "Management_WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/management?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGEMENTWEBSERVICE_WSDL_LOCATION = url;
        MANAGEMENTWEBSERVICE_EXCEPTION = e;
    }

    public ManagementWebService() {
        super(__getWsdlLocation(), MANAGEMENTWEBSERVICE_QNAME);
    }

    public ManagementWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGEMENTWEBSERVICE_QNAME, features);
    }

    public ManagementWebService(URL wsdlLocation) {
        super(wsdlLocation, MANAGEMENTWEBSERVICE_QNAME);
    }

    public ManagementWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGEMENTWEBSERVICE_QNAME, features);
    }

    public ManagementWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagementWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManagementWeb
     */
    @WebEndpoint(name = "Management_WebPort")
    public ManagementWeb getManagementWebPort() {
        return super.getPort(new QName("http://is_assignment3/", "Management_WebPort"), ManagementWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagementWeb
     */
    @WebEndpoint(name = "Management_WebPort")
    public ManagementWeb getManagementWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://is_assignment3/", "Management_WebPort"), ManagementWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGEMENTWEBSERVICE_EXCEPTION!= null) {
            throw MANAGEMENTWEBSERVICE_EXCEPTION;
        }
        return MANAGEMENTWEBSERVICE_WSDL_LOCATION;
    }

}
